using System;
using Foundation;
using UIKit;

namespace UsabillaIos
{
	[BaseType(typeof(NSObject), Name = "Usabilla"
        )]

    interface Usabilla
	{
        [Static, Export("initializeWithAppID:completion:")]
        void Initialize([NullAllowed]string appId, [NullAllowed]Action completion);

        [Static, Export("customVariables")]
        NSDictionary<NSString, NSObject> CustomVariables { get; set; }

        [Static, Export("delegate"), NullAllowed]
        UsabillaDelegate Delegate { get; set; }

        [Static, Export("localizedStringFile")]
        String LocalizedStringFile { get; set; }

        [Static, Export("theme")]
        UsabillaTheme Theme { get; set; }

        [Static, Export("dismissAutomatically")]
        bool DismissAutomatically { get; set; }

        [Static, Export("canDisplayCampaigns")]
        bool CanDisplayCampaigns { get; set; }

        [Static, Export("debugEnabled")]
        bool DebugEnabled { get; set; }

        [Static, Export("sendEvent:")]
        void SendEvent(string eventName);

        [Static, Export("removeCachedForms")]
        void RemoveCachedForms();

        [Static, Export("resetCampaignDataWithCompletion:")]
        void ResetCampaignData([NullAllowed]Action completion);

        [Static, Export("preloadFeedbackForms:")]
        void PreloadFeedbackForms(String[] formIDs);

        [Static, Export("loadFeedbackForm:screenshot:")]
        void LoadFeedbackForm(string formID, [NullAllowed]UIImage image);

        [Static, Export("takeScreenshot:")]
        [NullAllowed] UIImage TakeScreenshot(UIView view);

        [Static, Export("dismiss")]
        bool Dismiss();
    }

    [BaseType(typeof(NSObject))]
    [Model(AutoGeneratedName = true), Protocol]
    interface UsabillaDelegate
    {
        [Abstract]
        [Export("formDidLoadWithForm:")]
        void FormDidLoad(UINavigationController form);

        [Abstract]
        [Export("formDidFailLoadingWithError:")]
        void FormDidFailLoading(UBError form);

        [EventArgs("FormDidClose")]
        [Export("formDidCloseWithFormID:results:isRedirectToAppStoreEnabled:")]
        void FormDidClose(String formID, NSArray feedbackResults, bool isRedirectToAppStoreEnabled);

        [EventArgs("FormWillClose")]

        [Export("formWillCloseWithForm:formID:results:isRedirectToAppStoreEnabled:")]
        void FormWillClose(UINavigationController form, String formID, NSArray feedbackResults, bool isRedirectToAppStoreEnabled);

        [Export("campaignDidCloseWithFeedbackResult:isRedirectToAppStoreEnabled:")]
        [EventArgs("CampaignDidClose")]

        void CampaignDidClose(FeedbackResult feedbackResult, bool isRedirectToAppStoreEnabled);
    }
}
